"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type EventRow={id:number;title:string;category:string;start_date:string;end_date:string;start_time:string;location:string;description:string;status:string};
const monthName=new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"});
export default function CalendarPage(){
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)); const [events,setEvents]=useState<EventRow[]>([]); const [form,setForm]=useState({title:"",category:"Kegiatan",startDate:"",endDate:"",startTime:"",location:"",description:""}); const [error,setError]=useState("");
  const load=useCallback(async()=>{const from=new Date(month.getFullYear(),month.getMonth(),1).toISOString().slice(0,10);const to=new Date(month.getFullYear(),month.getMonth()+1,0).toISOString().slice(0,10);const r=await fetch(`/api/academic-events?from=${from}&to=${to}`);const j=await r.json() as {events?:EventRow[]};setEvents(j.events||[]);},[month]); useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const days=useMemo<Array<number|null>>(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1).getDay();const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const blanks:Array<number|null>=Array(first?first-1:6).fill(null);return blanks.concat([...Array(count)].map((_,i)=>i+1));},[month]);
  async function add(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/academic-events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const j=await r.json() as {error?:string};if(!r.ok){setError(j.error||"Agenda gagal disimpan.");return;}setForm({title:"",category:"Kegiatan",startDate:"",endDate:"",startTime:"",location:"",description:""});await load();}
  return <main className="calendar-page"><header><div><span>KALENDER PENDIDIKAN</span><h1>{monthName.format(month)}</h1><p>Agenda akademik, kegiatan pesantren, ujian, dan libur dalam satu kalender.</p></div><div className="calendar-nav"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><button onClick={()=>setMonth(new Date())}>Hari ini</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></header><section className="calendar-layout"><article className="card calendar-grid"><div className="calendar-weekdays">{["Sen","Sel","Rab","Kam","Jum","Sab","Min"].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-days">{days.map((day,i)=>{const date=day?`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`:"";const hits=events.filter(x=>date&&x.start_date<=date&&x.end_date>=date);return <div className={`calendar-day ${day?"":"empty"}`} key={`${date}-${i}`}>{day&&<strong>{day}</strong>}{hits.map(x=><span key={x.id} title={x.description}>{x.title}</span>)}</div>;})}</div></article><aside className="card calendar-form"><h2>Tambah Agenda</h2><form onSubmit={add}><label>Nama kegiatan<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Contoh: Ujian Tengah Semester"/></label><label>Kategori<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Kegiatan</option><option>Ujian</option><option>Libur</option><option>Rapat</option><option>PPDB</option></select></label><div className="form-grid"><label>Mulai<input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Selesai<input required type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div><label>Jam (opsional)<input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>Lokasi<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Catatan<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button">Simpan Agenda</button></form></aside></section><section className="card calendar-agenda"><h2>Daftar Agenda Bulan Ini</h2>{events.length?events.map(x=><div key={x.id}><b>{x.start_date}{x.end_date!==x.start_date?` – ${x.end_date}`:""}</b><span><strong>{x.title}</strong><small>{x.category}{x.start_time?` · ${x.start_time}`:""}{x.location?` · ${x.location}`:""}</small></span></div>):<p className="muted">Belum ada agenda pada bulan ini.</p>}</section></main>;
}
