"use client";
import { useEffect, useState } from "react";
import BrandMark from "../../brand-mark";

type Payload = { admission: Record<string, unknown>; rank: number; generatedAt: string };
const value = (row: Record<string, unknown>, key: string) => String(row[key] ?? "-") || "-";

export default function SPMBLetterPage() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState("");
  useEffect(() => { const id = new URLSearchParams(window.location.search).get("id") || ""; void fetch(`/api/ppdb/letter?id=${encodeURIComponent(id)}`, { cache: "no-store" }).then(async response => { const result = await response.json() as Payload & { error?: string }; if (!response.ok) throw new Error(result.error || "Surat gagal dimuat."); setData(result); if (new URLSearchParams(window.location.search).get("auto") === "1") setTimeout(() => window.print(), 400); }).catch(caught => setError(caught instanceof Error ? caught.message : "Surat gagal dimuat.")); }, []);
  if (error) return <main className="spmb-letter-error"><h1>Surat tidak dapat dimuat</h1><p>{error}</p></main>;
  if (!data) return <main className="spmb-letter-loading">Menyiapkan surat SPMB…</main>;
  const admission = data.admission;
  return <main className="spmb-letter-page"><div className="spmb-letter-actions no-print"><button onClick={() => window.close()}>← Kembali</button><button onClick={() => window.print()}>Cetak / Simpan PDF</button></div><article className="spmb-letter-sheet"><header className="spmb-letter-head"><BrandMark/><div><strong>PONDOK PESANTREN NURUL IMAN</strong><span>SISTEM INFORMASI NURUL IMAN · SINURMAN</span><small>Jl. Pendidikan Pesantren Nurul Iman</small></div></header><div className="spmb-letter-rule"/><section className="spmb-letter-title"><span>SPMB 2027–2028</span><h1>Surat Hasil Seleksi</h1><p>Nomor: {value(admission, "registration_no")}</p></section><p className="spmb-letter-body">Dengan ini Panitia Seleksi Penerimaan Murid Baru Pondok Pesantren Nurul Iman menyampaikan hasil seleksi calon santri berikut:</p><dl className="spmb-letter-details"><div><dt>Nama calon santri</dt><dd>{value(admission, "name")}</dd></div><div><dt>Jenjang pilihan</dt><dd>{value(admission, "desired_level")}</dd></div><div><dt>Nama wali</dt><dd>{value(admission, "guardian_name")}</dd></div><div><dt>Asal sekolah</dt><dd>{value(admission, "previous_school")}</dd></div><div><dt>Nilai seleksi</dt><dd>{value(admission, "score")} / 100</dd></div><div><dt>Peringkat gelombang</dt><dd>#{data.rank}</dd></div><div><dt>Status keputusan</dt><dd className="spmb-status-value">{value(admission, "status")}</dd></div></dl><p className="spmb-letter-body">Keputusan ini diterbitkan berdasarkan verifikasi dokumen dan tahapan seleksi yang tercatat dalam sistem SINURMAN. Simpan surat ini sebagai bukti resmi dan ikuti jadwal daftar ulang yang diinformasikan panitia.</p><section className="spmb-letter-sign"><div><span>Mengetahui,</span><strong>Panitia SPMB</strong><i/><b>(__________________)</b></div><div><span>Nurul Iman, {new Intl.DateTimeFormat("id-ID", { dateStyle: "long" }).format(new Date(data.generatedAt))}</span><strong>Pimpinan Pesantren</strong><i/><b>(__________________)</b></div></section><footer>Dokumen diterbitkan otomatis oleh SINURMAN · Verifikasi keaslian melalui nomor pendaftaran di portal SPMB.</footer></article></main>;
}
